name: Fork自动同步上游仓库
on:
  # 北京时间 每日凌晨4点自动拉取（UTC 20:00）
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch: # 网页支持手动一键触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 同步上游 FGBLH/HKL main分支
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: FGBLH/HKL
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
