name: Fork自动同步上游仓库

on:
  # 北京时间每日凌晨 4:00（UTC 20:00）
  schedule:
    - cron: '0 20 * * *'

  # 支持网页手动触发
  workflow_dispatch:

# GitHub Actions 权限
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 同步上游 FGBLH/HKL main 分支
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: FGBLH/HKL
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
